title: Olusegun Mayungbe Blog
author: @oluadepe
email: o.mayungbe@oluadepefarms.com
description: > # this means to ignore newlines until "baseurl:"
  This site is to give you more details about what I do
My passion
My mission

# social links
twitter_username: mayour26 # DO NOT include the @ character, or else the build will fail!
github_username:  oluadepe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
